### ISSUE TITLE
Image Resolution Problem - Downloaded Images at 846x1202 Instead of 908x1264

### ISSUE THREAD

**Issue by AkiZZZZZ** [vsatyamesc/Gammaplus-Takeshobo-Downloader#1]
**Description:** I am experiencing an issue with the current implementation of the script where the downloaded images have a resolution of 846x1202, but the correct resolution should be 908x1264.

**Details:** Upon reviewing the code, I noticed that the script relies on the views field contained within the ptimg.json file to process and stitch the images. However, the resolution specified in the views field does not match the original resolution of 908x1264. This discrepancy leads to the images being downloaded at a lower resolution of 846x1202.

**Question:** Is this script limited to downloading images at the resolution specified in the views field? If so, is there a way to modify the script to download the images at the correct resolution of 908x1264?

**The manga URL:** https://gammaplus.takeshobo.co.jp/_files/imaizuminchiha/30/

846x1202 resolution (download by this script)
![0001](https://github.com/user-attachments/assets/c1d2d630-b243-4334-a1cf-e95f34cfc5f9)

908x1264 resolution (download by F12)
![0001](https://github.com/user-attachments/assets/3d31fde6-f247-40d9-a325-2d9ce357a26c)

**Comment by vsatyamesc** [comment]
Old: They must have increase the image size. I need to code it again. You've got it right, the given image is a puzzle and I just solve it through code.

Edit: Upon reviewing the code and the image; I've found everything is right and working perfect. They've just overlapped almost 1 pixel per 1 block / of 64 blocks.

**Comment by AkiZZZZZ** [comment]
Thanks for you job!
